jest.setTimeout(3000000)

import * as path from 'path'
import * as fs from 'fs'

import {
    loadData,
    execute,
    executeSuite,
} from './suites'

describe('Test verify on chain', () => {
    const data = loadData('suites.json')
    const test = data.suites[0]

    it("verifyTallyResult", async () => {
        const result = await executeSuite(test, expect)
        expect(result).toBeTruthy()

	// get tally data generated by executeSuite
	const tally = JSON.parse(fs.readFileSync(path.join(__dirname, '../../../cli/tally.json')).toString())

        // verify tally result on chain
        const voteOptionIndex = 0
	const voteOptionTreeDepth = 2
        const verifyTallyResultCommand = `node build/index.js verifyTallyResult` +
                ` -x ${tally.maci}` +
                ` -o ${tally.pollId}` +
                ` -v ${voteOptionIndex}` +
                ` -d ${voteOptionTreeDepth}` +
                ` -t tally.json`

	expect(() => execute(verifyTallyResultCommand)).toThrow(/verifyTallyResult returns FALSE/)
    })
})
