jest.setTimeout(3000000)

import * as fs from 'fs'
import * as path from 'path'

import {
    loadData,
    execute,
    executeSuite,
} from './suites'

describe('Test verifyPerVOSpentVoiceCredits on chain', () => {
    const data = loadData('suites.json')
    const test = data.suites[0] 
    it(test.name, async () => {
        const result = await executeSuite(test, expect)
        console.log(result)
        expect(result).toBeTruthy()

        // get tally data generated by executeSuite
        const tally = JSON.parse(fs.readFileSync(path.join(__dirname, '../../../cli/tally.json')).toString())

	const voteOptionTreeDepth = 2
	const voteOptionIndex = 0
        const verifyPerVOSpentVoiceCreditsCommand = `node build/index.js verifyPerVOSpentVoiceCredits` +
            ` -x ${tally.maci}` +
            ` -o ${tally.pollId}` +
            ` -v ${voteOptionIndex}` +
            ` -d ${voteOptionTreeDepth}` +
            ` -t tally.json`

	let verified = false
	try {
	    execute(verifyPerVOSpentVoiceCreditsCommand)
	    verified = true
	} catch (e) {
            console.log(e)
	}
	expect(verified).toEqual(true)
    })
})
