// auto-generated by circomkit
pragma circom 2.0.0;

include ".././core/qv/processMessages.circom";

component main {public[numSignUps, index, batchEndIndex, msgRoot, currentSbCommitment, newSbCommitment, pollEndTimestamp, actualStateTreeDepth]} = ProcessMessages(10, 2, 1, 2);
