/** Declaration file generated by dts-gen */

declare module 'optimisedmt' {
    export class OptimisedMT {
        depth: number;
        zeroValue: bigint;
        leavesPerNode: number;
        hashFunc: (leaves: bigint[]) => bigint;
        nextIndex: number;
        zeros: bigint[];
        root: bigint;
        nodes: any;
        numNodes: number;
        capacity: number;
        constructor(_depth: number, _zeroValue: bigint, _leavesPerNode: number, _hashFunc: (leaves: bigint[]) => bigint);

        copy(): OptimisedMT;

        genMerklePath(_index: number): any;

        genMerkleSubrootPath(_startIndex: number, _endIndex: number): any;

        getChildIndices(_index: number): number[];

        getLeaf(_index: number): bigint;

        getNode(_index: number): bigint;

        getParentIndices(_index: number): number[];

        insert(_value: bigint): void;

        setNode(_index: number, _value: bigint): void;

        update(_index: number, _value: bigint): void;

        serialize(): string;

        static calcChildIndices(_index: number, _leavesPerNode: number, _depth: number): number[];

        static calcParentIndices(_index: number, _leavesPerNode: number, _depth: number): number[];

        static unserialize(s: string): OptimisedMT;

        static verifyMerklePath(_proof: any, _hashFunc: (leaves: bigint[]) => bigint): any;

    }
}